// frontend/src/views/auth/Register.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useRouter } from 'vue-router';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { request } from '@/lib/utils';
import { ENDPOINTS } from '@/lib/api';

const router = useRouter();
const username = ref('');
const password = ref('');
const confirmPassword = ref('');
const agreeToTerms = ref(false);
const isLoading = ref(false);
const errorMessage = ref('');
const validationErrors = ref({
  password: '',
  confirm: '',
});

// 校验规则：长度 > 6，且包含英文和数字
const validatePassword = (val: string) => {
  if (!val) return '';
  if (val.length <= 6) return '密码必须大于 6 位';
  const hasEnglish = /[a-zA-Z]/.test(val);
  const hasNumber = /[0-9]/.test(val);
  if (!hasEnglish || !hasNumber) return '密码必须同时包含英文和数字';
  return '';
};

// 监听密码变化，实时校验
watch(password, (newVal) => {
  validationErrors.value.password = validatePassword(newVal);
  // 如果确认密码已经填了，也要触发一致性校验
  if (confirmPassword.value) {
    validationErrors.value.confirm = newVal !== confirmPassword.value ? '两次输入的密码不一致' : '';
  }
});

// 监听确认密码变化，实时校验一致性
watch(confirmPassword, (newVal) => {
  validationErrors.value.confirm = newVal !== password.value ? '两次输入的密码不一致' : '';
});

const isFormValid = computed(() => {
  return (
    username.value &&
    password.value &&
    confirmPassword.value &&
    agreeToTerms.value &&
    !validationErrors.value.password &&
    !validationErrors.value.confirm &&
    !isLoading.value
  );
});

const handleRegister = async () => {
  if (!isFormValid.value) return;

  isLoading.value = true;
  errorMessage.value = '';

  try {
    await request(ENDPOINTS.AUTH.REGISTER, {
      method: 'POST',
      body: JSON.stringify({
        username: username.value,
        password: password.value,
      }),
    });

    // 注册成功，跳转到登录页
    router.push('/login');
  } catch (error: unknown) {
    // 处理由 request 函数抛出的错误
    const message = error instanceof Error ? error.message : '注册失败，请稍后再试';
    errorMessage.value = message;
    console.error('Register error:', error);
  } finally {
    isLoading.value = false;
  }
};
</script>

<template>
  <div class="h-full flex items-center justify-center bg-gray-50/50 px-4 py-12 sm:px-6 lg:px-8">
    <Card class="w-full max-w-md shadow-lg">
      <CardHeader class="space-y-1 text-center">
        <CardTitle class="text-2xl font-bold tracking-tight">创建新账号</CardTitle>
        <CardDescription> 注册以加入 BNDSphere </CardDescription>
      </CardHeader>

      <CardContent class="space-y-4">
        <!-- 错误提示 -->
        <div
          v-if="errorMessage"
          class="bg-destructive/10 text-destructive text-sm p-3 rounded-md text-center"
        >
          {{ errorMessage }}
        </div>

        <div class="space-y-2">
          <label for="username" class="text-sm font-medium leading-none"> 用户名 </label>
          <input
            id="username"
            v-model="username"
            type="text"
            placeholder="账号名称"
            class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            @keyup.enter="handleRegister"
          />
        </div>

        <div class="space-y-2">
          <label for="password" class="text-sm font-medium leading-none"> 密码 </label>
          <input
            id="password"
            v-model="password"
            type="password"
            placeholder="必须包含英文和数字，且大于 6 位"
            :class="[
              'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
              validationErrors.password
                ? 'border-destructive ring-destructive/20 focus-visible:ring-destructive'
                : '',
            ]"
            @keyup.enter="handleRegister"
          />
          <p v-if="validationErrors.password" class="text-[12px] font-medium text-destructive">
            {{ validationErrors.password }}
          </p>
        </div>

        <div class="space-y-2">
          <label for="confirmPassword" class="text-sm font-medium leading-none"> 确认密码 </label>
          <input
            id="confirmPassword"
            v-model="confirmPassword"
            type="password"
            placeholder=""
            :class="[
              'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
              validationErrors.confirm
                ? 'border-destructive ring-destructive/20 focus-visible:ring-destructive'
                : '',
            ]"
            @keyup.enter="handleRegister"
          />
          <p v-if="validationErrors.confirm" class="text-[12px] font-medium text-destructive">
            {{ validationErrors.confirm }}
          </p>
        </div>

        <!-- 隐私协议 -->
        <div class="flex items-center space-x-2 pt-2 group">
          <Checkbox
            id="terms"
            v-model="agreeToTerms"
            class="cursor-pointer transition-all hover:ring-2 hover:ring-primary/40 hover:border-primary"
          />
          <label
            for="terms"
            class="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer"
          >
            我已阅读并同意
            <a href="#" class="text-primary hover:underline" @click.stop>《用户隐私协议》</a>
          </label>
        </div>
      </CardContent>

      <CardFooter class="flex flex-col gap-4">
        <Button class="w-full" size="lg" :disabled="!isFormValid" @click="handleRegister">
          {{ isLoading ? '提交中...' : '立即注册' }}
        </Button>
        <div class="text-center text-sm text-muted-foreground">
          已有账号？
          <router-link to="/login" class="text-primary hover:underline font-medium">
            立即登录
          </router-link>
        </div>
      </CardFooter>
    </Card>
  </div>
</template>

// frontend/src/pages/Register.tsx
import React, { useState } from "react";
import { motion } from "motion/react";
import { UserPlus } from "@/src/components/ui/Icons";
import { useNavigate } from "react-router-dom";
import { client } from "../api/client";
import { StatusMessage } from "../components/ui/AppPrimitives";

export function Register() {
  const navigate = useNavigate();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState<unknown>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (password !== confirmPassword) {
      setError("两次输入的密码不一致。");
      return;
    }

    setIsLoading(true);

    try {
      const { data, error: apiError } = await client.POST("/api/v1/auth/register", {
        body: {
          username,
          password,
        },
      });

      if (apiError) {
        setError(apiError);
        return;
      }

      if (data) {
        // Automatically login after register or redirect to login page
        navigate("/login");
      }
    } catch (err: any) {
      setError(err);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="flex flex-col items-center justify-center min-h-[70vh] px-4"
    >
      <div className="w-full max-w-md bg-white p-8 rounded-md border border-slate-100 shadow-sm relative overflow-hidden">
        <div className="flex flex-col gap-2 mb-8 text-center relative z-10">
          <div className="mx-auto bg-primary-50 p-3 rounded-md text-primary-600 mb-2">
            <UserPlus size={28} />
          </div>
          <h1 className="text-2xl font-display font-bold text-slate-900">注册 BNDSphere</h1>
          <p className="text-slate-500 text-sm">创建您的新账号</p>
        </div>

        {error && (
          <div className="mb-6 relative z-10">
            <StatusMessage value={error} />
          </div>
        )}

        <form onSubmit={handleRegister} className="flex flex-col gap-5 relative z-10">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1.5 ml-1">用户名</label>
            <input
              type="text"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-md focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 outline-none transition-all font-medium text-slate-900"
              placeholder="您的用户名"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1.5 ml-1">密码</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-md focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 outline-none transition-all font-medium text-slate-900"
              placeholder="••••••••"
              required
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-1.5 ml-1">确认密码</label>
            <input
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-md focus:ring-2 focus:ring-primary-500/20 focus:border-primary-500 outline-none transition-all font-medium text-slate-900"
              placeholder="••••••••"
              required
            />
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="mt-4 w-full py-3.5 bg-primary-500 hover:bg-primary-600 text-white font-semibold rounded-md transition-all active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed shadow-md shadow-primary-500/20"
          >
            {isLoading ? "正在注册..." : "注册"}
          </button>

          <div className="mt-4 text-center text-sm text-slate-500">
            已有账号？{" "}
            <span
              onClick={() => navigate("/login")}
              className="text-primary-600 hover:text-primary-700 font-medium cursor-pointer"
            >
              返回登录
            </span>
          </div>
        </form>
      </div>
    </motion.div>
  );
}
